<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: 
The initial data. These are the features that you are using to train models and make predictions
### Hidden Layer:
The h layer between the input and output layers where all the calculations are made.
### Output Layer:
The product of the calculations given the input.
### Neuron: 
The mathematical calculation that takes an input and produces the output. The neuron is represented by the path from input layer to output layer.
### Weight: 
Weights are the impact that the hidden layer node has on the input in order to produce an output.
### Activation Function: 
The function used to produce the output
### Node Map:
The chart mapping the neural network showing the series of nodes from input to output.
### Perceptron:
Perceptron is a type of neural network and linear classification algorithm that uses the heaveside step function as an activator function. 

## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [393]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [394]:
##### Your Code Here #####
import numpy as np
df['b'] = np.ones((4,), dtype=int) # add bias
inputs = df.drop(columns='y').to_numpy()
output = df['y'].to_numpy()
weights = 2 * np.random.random((3,1)) - 1

In [395]:
weighted_sum = np.dot(inputs, weights)
weighted_sum

array([[0.75839693],
       [1.14906551],
       [1.39150325],
       [1.78217183]])

In [396]:
activated_output = sigmoid(weighted_sum)
activated_output

array([[0.68100559],
       [0.75934019],
       [0.80083212],
       [0.85596484]])

In [397]:
df['y'].to_numpy() - activated_output.T

array([[ 0.31899441,  0.24065981,  0.19916788, -0.85596484]])

In [398]:
error = output - activated_output.T
error

array([[ 0.31899441,  0.24065981,  0.19916788, -0.85596484]])

In [399]:
adjustments = error.T * sigmoid_derivative(activated_output)
adjustments

array([[ 0.07117279],
       [ 0.05226235],
       [ 0.04259047],
       [-0.17912771]])

In [400]:
weights += np.dot(inputs.T, adjustments)

In [401]:
np.dot(inputs.T, adjustments)

array([[-0.12686536],
       [-0.13653724],
       [-0.0131021 ]])

In [402]:
weights

array([[0.26380322],
       [0.49656908],
       [0.74529483]])

In [407]:
# Steps we've already done: 
# 1. Randomly Initialized Weights already. Those are in memory as `weights`
# 2. We've already got input data & correct_outputs


# Update our weights 100,000 times
for iteration in range(100000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Cac error
    error = output - activated_output.T
    
    adjustments = error.T * sigmoid_derivative(activated_output)
    
    # Update the Weights
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[-16.80370103]
 [-16.80370103]
 [ 25.25373517]]
Output after training
[[1.00000000e+00]
 [9.99786151e-01]
 [9.99786151e-01]
 [2.35477783e-04]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [241]:
np.exp(-1)

0.36787944117144233

In [346]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [441]:
from sklearn.preprocessing import MinMaxScaler, Normalizer
feats = list(diabetes)[:-1]
scaler = Normalizer()
X = diabetes[feats]
X['bias'] = np.ones((len(diabetes),), dtype=int)
X_scaled = scaler.fit_transform(X, y)
y = diabetes['Outcome'].to_numpy()

In [472]:
##### Update this Class #####

class Perceptron(object):
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1-sx)

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """

        # Randomly Initialize Weights
        self.weights = 2 * np.random.random((9,1)) - 1

        for i in range(self.niter):
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(X, self.weights)
            # Activate!
            activated_output = sigmoid(weighted_sum)
            # Cac error
            error = y - activated_output.T
        
            adjustments = error.T * sigmoid_derivative(activated_output)
        
            # Update the Weights
            self.weights += np.dot(X.T, adjustments)
        
            
    def predict(self, X):
        """Return class label after unit step"""
        pred = np.dot(X, self.weights)
        return np.where(pred > 0, 1, 0)

In [473]:
nn = Perceptron(niter=10000)

In [483]:
nn.fit(X_scaled,y)

In [475]:
y[:10]

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1], dtype=int64)

In [484]:
y_pred = nn.predict(X_scaled)
y_pred[:30]

array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0]])

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?